version: "3"
networks:
  backend:
    driver: bridge
    name: backend
  frontend:
    driver: bridge
    name: frontend
services:
    db:
        build: ./mongo/
        image: "db"
        container_name: db
        ports:
          - "27017:27017"
        networks:
            - backend
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 40s
    server:
        build:
          context: ./servercode/
          args:
            newip: db
        image: "server"
        container_name: server
        ports:
          - "3000:3000"
        networks:
          - backend
        depends_on:
          - db
    ui:
        build:
          context: ./clientcode/
          args:
            newip: server
        image: "ui"
        container_name: ui
        ports:
          - "8000:8000"
        networks:
          - backend
          - frontend
        depends_on:
          - db
